<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch;

/**
 * A common representation of an error on the FamilySearch platform.
 */
class Error
{

    /**
     * The error code. Intepreted per &lt;a href=&quot;http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html&quot;&gt;RFC 2616, Section 10 (HTTP Status Code Definitions)&lt;/a&gt;.
     *
     * @var integer
     */
    private $code;

    /**
     * A text label associated with the error code.
     *
     * @var string
     */
    private $label;

    /**
     * A message associated with the error.
     *
     * @var string
     */
    private $message;

    /**
     * The back-end stack trace associated with the error, useful for debugging.
     *
     * @var string
     */
    private $stacktrace;

    /**
     * Constructs a Error from a (parsed) JSON hash
     *
     * @param array $o
     */
    public function __construct($o = null)
    {
        if ($o) {
            $this->initFromArray($o);
        }
    }

    /**
     * The error code. Intepreted per &lt;a href=&quot;http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html&quot;&gt;RFC 2616, Section 10 (HTTP Status Code Definitions)&lt;/a&gt;.
     *
     * @return integer
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * The error code. Intepreted per &lt;a href=&quot;http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html&quot;&gt;RFC 2616, Section 10 (HTTP Status Code Definitions)&lt;/a&gt;.
     *
     * @param integer $code
     */
    public function setCode($code)
    {
        $this->code = $code;
    }
    /**
     * A text label associated with the error code.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * A text label associated with the error code.
     *
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
    }
    /**
     * A message associated with the error.
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * A message associated with the error.
     *
     * @param string $message
     */
    public function setMessage($message)
    {
        $this->message = $message;
    }
    /**
     * The back-end stack trace associated with the error, useful for debugging.
     *
     * @return string
     */
    public function getStacktrace()
    {
        return $this->stacktrace;
    }

    /**
     * The back-end stack trace associated with the error, useful for debugging.
     *
     * @param string $stacktrace
     */
    public function setStacktrace($stacktrace)
    {
        $this->stacktrace = $stacktrace;
    }
    /**
     * Returns the associative array for this Error
     *
     * @return array
     */
    public function toArray()
    {
        $a = array();
        if ($this->code) {
            $a["code"] = $this->code;
        }
        if ($this->label) {
            $a["label"] = $this->label;
        }
        if ($this->message) {
            $a["message"] = $this->message;
        }
        if ($this->stacktrace) {
            $a["stacktrace"] = $this->stacktrace;
        }
        return $a;
    }

    /**
     * Returns the JSON string for this Error
     *
     * @return string
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }

    /**
     * Initializes this Error from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        if (isset($o['code'])) {
                $this->code = $o["code"];
        }
        if (isset($o['label'])) {
                $this->label = $o["label"];
        }
        if (isset($o['message'])) {
                $this->message = $o["message"];
        }
        if (isset($o['stacktrace'])) {
                $this->stacktrace = $o["stacktrace"];
        }
    }
}
