<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch;

/**
 * A tag in the FamilySearch system.
 */
class Tag
{

    /**
     * A reference to the value of the tag.
     *
     * @var string
     */
    private $resource;

    /**
     * Constructs a Tag from a (parsed) JSON hash
     *
     * @param array $o
     */
    public function __construct($o = null)
    {
        if ($o) {
            $this->initFromArray($o);
        }
    }

    /**
     * A reference to the value of the tag.
     *
     * @return string
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * A reference to the value of the tag.
     *
     * @param string $resource
     */
    public function setResource($resource)
    {
        $this->resource = $resource;
    }
    /**
     * Returns the associative array for this Tag
     *
     * @return array
     */
    public function toArray()
    {
        $a = array();
        if ($this->resource) {
            $a["resource"] = $this->resource;
        }
        return $a;
    }

    /**
     * Returns the JSON string for this Tag
     *
     * @return string
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }

    /**
     * Initializes this Tag from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        if (isset($o['resource'])) {
            $this->resource = $o["resource"];
        }
    }
}
