<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Common;

/**
 * A note about a genealogical resource (e.g. conclusion or source).
 */
class Note extends \Gedcomx\Links\HypermediaEnabledData 
{
    
    /**
     * The language of the note.
     */
    private $lang;

    /**
     * The subject of the note.
     */
    private $subject;
    /**
     * The text of the note.
     */
    private $text;
    /**
     * Attribution metadata for a note.
     */
    private $attribution;

    /**
     * Constructs a Note from a (parsed) JSON hash
     */
    public function __construct($o = null) {
      if( $o ) {
        $this->initFromArray($o);
      }
    }

    /**
     * The language of the note.
     */
    public function getLang() {
      return $this->lang;
    }

    /**
     * The language of the note.
     */
    public function setLang($lang) {
      $this->lang = $lang;
    }
    /**
     * The subject of the note.
     */
    public function getSubject() {
      return $this->subject;
    }

    /**
     * The subject of the note.
     */
    public function setSubject($subject) {
      $this->subject = $subject;
    }
    /**
     * The text of the note.
     */
    public function getText() {
      return $this->text;
    }

    /**
     * The text of the note.
     */
    public function setText($text) {
      $this->text = $text;
    }
    /**
     * Attribution metadata for a note.
     */
    public function getAttribution() {
      return $this->attribution;
    }

    /**
     * Attribution metadata for a note.
     */
    public function setAttribution($attribution) {
      $this->attribution = $attribution;
    }
    /**
     * Returns the associative array for this Note
     */
    public function toArray() {
      $a = parent::toArray();
      if( $this->lang ) {
            $a["lang"] = $this->lang;
      }
      if( $this->subject ) {
            $a["subject"] = $this->subject;
      }
      if( $this->text ) {
            $a["text"] = $this->text;
      }
      if( $this->attribution ) {
            $a["attribution"] = $this->attribution->toArray();
      }
      return $a;
    }


    /**
     * Initializes this Note from an associative array
     */
    public function initFromArray($o) {
      parent::initFromArray($o);
      if( isset($o['lang']) ) {
            $this->lang = $o["lang"];
      }
      if( isset($o['subject']) ) {
            $this->subject = $o["subject"];
      }
      if( isset($o['text']) ) {
            $this->text = $o["text"];
      }
      if( isset($o['attribution']) ) {
            $this->attribution = new \Gedcomx\Common\Attribution($o["attribution"]);
      }
    }
}
