<?php

/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

  namespace Gedcomx\Common {

    /**
     * A data qualifier. Qualifiers are used to "qualify" certain data elements to provide additional context, information, or details.
     */
    class Qualifier  {
    
    
      /**
       * The value of the qualifier.
       */
      private $value;

      /**
       * Constructs a Qualifier from a (parsed) JSON hash
       */
      public function __construct($o = null) {
        if( $o ) {
          $this->initFromArray($o);
        }
      }
      
      /**
       * The value of the qualifier.
       */
      public function getValue() {
        return $this->value;
      }
      
      /**
       * The value of the qualifier.
       */
      public function setValue($value) {
        $this->value = $value;
      }
      /**
       * Returns the associative array for this Qualifier
       */
      public function toArray() {
        $a = array();
        if( $this->value ) {
          $a["value"] = $this->value;
        }
        return $a;
      }
      
      /**
       * Returns the JSON string for this Qualifier
       */
      public function toJson() {
        return json_encode($this->toArray());
      }

      /**
       * Initializes this Qualifier from an associative array
       */
      public function initFromArray($o) {
        if( isset($o['value']) ) {
          $this->value = $o["value"];
        }
      }
    
    }
    
  }

?>
