<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch\Discussions;

/**
 * 
 */
class Comment extends \Gedcomx\Links\HypermediaEnabledData
{

    /**
     * The text or &quot;message body&quot; of the comment
     *
     * @var string
     */
    private $text;

    /**
     * date of creation
     *
     * @var integer
     */
    private $created;

    /**
     * contributor of comment
     *
     * @var \Gedcomx\Common\ResourceReference
     */
    private $contributor;

    /**
     * Constructs a Comment from a (parsed) JSON hash
     *
     * @param array $o
     */
    public function __construct($o = null)
    {
        if ($o) {
            $this->initFromArray($o);
        }
    }

    /**
     * The text or &quot;message body&quot; of the comment
     *
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * The text or &quot;message body&quot; of the comment
     *
     * @param string $text
     */
    public function setText($text)
    {
        $this->text = $text;
    }
    /**
     * date of creation
     *
     * @return integer
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * date of creation
     *
     * @param integer $created
     */
    public function setCreated($created)
    {
        $this->created = $created;
    }
    /**
     * contributor of comment
     *
     * @return \Gedcomx\Common\ResourceReference
     */
    public function getContributor()
    {
        return $this->contributor;
    }

    /**
     * contributor of comment
     *
     * @param \Gedcomx\Common\ResourceReference $contributor
     */
    public function setContributor($contributor)
    {
        $this->contributor = $contributor;
    }
    /**
     * Returns the associative array for this Comment
     *
     * @return array
     */
    public function toArray()
    {
        $a = parent::toArray();
        if ($this->text) {
            $a["text"] = $this->text;
        }
        if ($this->created) {
            $a["created"] = $this->created;
        }
        if ($this->contributor) {
            $a["contributor"] = $this->contributor->toArray();
        }
        return $a;
    }


    /**
     * Initializes this Comment from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        parent::initFromArray($o);
        if (isset($o['text'])) {
                $this->text = $o["text"];
        }
        if (isset($o['created'])) {
                $this->created = $o["created"];
        }
        if (isset($o['contributor'])) {
                $this->contributor = new \Gedcomx\Common\ResourceReference($o["contributor"]);
        }
    }
}
