language: php
sudo: false
php:
- 5.6
- 5.5
- 5.4
- 5.3
install: composer install
env:
  global:
    secure: KCnHgwpoCxmVjIeUUbyaGjoFONPde9BDW42nhV+fuEhGDU3cS83aSkaOqLBbF4ohYlOb+65WbW2SK5ec/kRxEdTNGPWlwUkVSUXuhwut2hdyuR1I0eHc4o5YuxcOknbhNbquqSx6CkldQUgcxNgrBjqxpO9au1F+DfmCn4fS1Qw=
after_success:
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh docs.sh; fi
  