<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch\Platform\Tree;

/**
 * The set of operations applicable to FamilySearch data.
 */
class ChangeOperation
{

    /**
     * (no documentation provided)
     */
    const CREATE = "http://familysearch.org/v1/Create";

    /**
     * (no documentation provided)
     */
    const READ = "http://familysearch.org/v1/Read";

    /**
     * (no documentation provided)
     */
    const UPDATE = "http://familysearch.org/v1/Update";

    /**
     * (no documentation provided)
     */
    const DELETE = "http://familysearch.org/v1/Delete";

    /**
     * (no documentation provided)
     */
    const MERGE = "http://familysearch.org/v1/Merge";

    /**
     * (no documentation provided)
     */
    const UNMERGE = "http://familysearch.org/v1/Unmerge";

    /**
     * (no documentation provided)
     */
    const RESTORE = "http://familysearch.org/v1/Restore";
}
