<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch\Platform\Tree;

/**
 * Information about a match.
 */
class MatchInfo
{

    /**
     * The way this match has been resolved.
     *
     * @var string
     */
    private $status;

    /**
     * The collection in which this match was found.
     *
     * @var string
     */
    private $collection;

    /**
     * Constructs a MatchInfo from a (parsed) JSON hash
     *
     * @param mixed $o Either an array (JSON) or an XMLReader.
     */
    public function __construct($o = null)
    {
        if (is_array($o)) {
            $this->initFromArray($o);
        }
        else if ($o instanceof \XMLReader) {
            $success = true;
            while ($success && $o->nodeType != \XMLReader::ELEMENT) {
                $success = $o->read();
            }
            if ($o->nodeType != \XMLReader::ELEMENT) {
                throw new \Exception("Unable to read XML: no start element found.");
            }

            $this->initFromReader($o);
        }
    }

    /**
     * The way this match has been resolved.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * The way this match has been resolved.
     *
     * @param string $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }
    /**
     * The collection in which this match was found.
     *
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * The collection in which this match was found.
     *
     * @param string $collection
     */
    public function setCollection($collection)
    {
        $this->collection = $collection;
    }
    /**
     * Returns the associative array for this MatchInfo
     *
     * @return array
     */
    public function toArray()
    {
        $a = array();
        if ($this->status) {
            $a["status"] = $this->status;
        }
        if ($this->collection) {
            $a["collection"] = $this->collection;
        }
        return $a;
    }

    /**
     * Returns the JSON string for this MatchInfo
     *
     * @return string
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }

    /**
     * Initializes this MatchInfo from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        if (isset($o['status'])) {
            $this->status = $o["status"];
        }
        if (isset($o['collection'])) {
            $this->collection = $o["collection"];
        }
    }

    /**
     * Initializes this MatchInfo from an XML reader.
     *
     * @param \XMLReader $xml The reader to use to initialize this object.
     */
    public function initFromReader($xml)
    {
        $empty = $xml->isEmptyElement;

        if ($xml->hasAttributes) {
            $moreAttributes = $xml->moveToFirstAttribute();
            while ($moreAttributes) {
                if (!$this->setKnownAttribute($xml)) {
                    //skip unknown attributes...
                }
                $moreAttributes = $xml->moveToNextAttribute();
            }
        }

        if (!$empty) {
            $xml->read();
            while ($xml->nodeType != \XMLReader::END_ELEMENT) {
                if ($xml->nodeType != \XMLReader::ELEMENT) {
                    //no-op: skip any insignificant whitespace, comments, etc.
                }
                else if (!$this->setKnownChildElement($xml)) {
                    $n = $xml->localName;
                    $ns = $xml->namespaceURI;
                    //skip the unknown element
                    while ($xml->nodeType != \XMLReader::END_ELEMENT && $xml->localName != $n && $xml->namespaceURI != $ns) {
                        $xml->read();
                    }
                }
                $xml->read(); //advance the reader.
            }
        }
    }


    /**
     * Sets a known child element of MatchInfo from an XML reader.
     *
     * @param \XMLReader $xml The reader.
     * @return bool Whether a child element was set.
     */
    protected function setKnownChildElement($xml) {
        return false;
    }

    /**
     * Sets a known attribute of MatchInfo from an XML reader.
     *
     * @param \XMLReader $xml The reader.
     * @return bool Whether an attribute was set.
     */
    protected function setKnownAttribute($xml) {
        if (($xml->localName == 'status') && (empty($xml->namespaceURI))) {
            $this->status = $xml->value;
            return true;
        }
        if (($xml->localName == 'collection') && (empty($xml->namespaceURI))) {
            $this->collection = $xml->value;
            return true;
        }

        return false;
    }

    /**
     * Writes this MatchInfo to an XML writer.
     *
     * @param \XMLWriter $writer The XML writer.
     * @param bool $includeNamespaces Whether to write out the namespaces in the element.
     */
    public function toXml($writer, $includeNamespaces = true)
    {
        $writer->startElementNS('fs', 'matchInfo', null);
        if ($includeNamespaces) {
            $writer->writeAttributeNs('xmlns', 'fs', null, 'http://familysearch.org/v1/');
        }
        $this->writeXmlContents($writer);
        $writer->endElement();
    }

    /**
     * Writes the contents of this MatchInfo to an XML writer. The startElement is expected to be already provided.
     *
     * @param \XMLWriter $writer The XML writer.
     */
    public function writeXmlContents($writer)
    {
        if ($this->status) {
            $writer->writeAttribute('status', $this->status);
        }
        if ($this->collection) {
            $writer->writeAttribute('collection', $this->collection);
        }
    }
}
