<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch\Tree;

/**
 * Enumeration of the possible change object modifiers.
 */
class ChangeObjectModifier
{

    /**
     *  The person.
     */
    const Person = "http://gedcomx.org/Person";

    /**
     *  The couple.
     */
    const Couple = "http://gedcomx.org/Couple";

    /**
     *  The child-and-parents relationship.
     */
    const ChildAndParentsRelationship = "http://familysearch.org/v1/ChildAndParentsRelationship";

}
