<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Extensions\FamilySearch\Tree;

/**
 * Enumeration of the possible change object types.
 */
class ChangeObjectType
{

    /**
     *  A person was changed.
     */
    const PERSON = "http://gedcomx.org/Person";

    /**
     *  A couple relationship was changed.
     */
    const COUPLE = "http://gedcomx.org/Couple";

    /**
     *  A couple-child relationship was changed.
    *  @deprecated use {@link #ChildAndParentsRelationship}
     */
    const COUPLECHILDRELATIONSHIP = "http://familysearch.org/v1/CoupleChildRelationship";

    /**
     * (no documentation provided)
     */
    const CHILDANDPARENTSRELATIONSHIP = "http://familysearch.org/v1/ChildAndParentsRelationship";

    /**
     *  The man in a couple relationship was changed.
     */
    const MAN = "http://familysearch.org/v1/Man";

    /**
     *  The man in a couple relationship was changed.
     */
    const WOMAN = "http://familysearch.org/v1/Woman";

    /**
     *  The father in a couple-child relationship was changed.
     */
    const FATHER = "http://familysearch.org/v1/Father";

    /**
     *  The mother in a couple-child relationship was changed.
     */
    const MOTHER = "http://familysearch.org/v1/Mother";

    /**
     *  The child in a couple-child relationship was changed.
     */
    const CHILD = "http://familysearch.org/v1/Child";

    /**
     *  A source reference was changed.
     */
    const SOURCEREFERENCE = "http://gedcomx.org/SourceReference";

    /**
     *  A discussion reference was changed.
     */
    const DISCUSSIONREFERENCE = "http://familysearch.org/v1/DiscussionReference";

    /**
     *  An evidence reference was changed.
     */
    const EVIDENCEREFERENCE = "http://familysearch.org/v1/EvidenceReference";

    /**
     *  An affiliation fact was changed.
     */
    const AFFILIATION = "http://familysearch.org/v1/Affiliation";

    /**
     *  A bar mitzvah was changed.
     */
    const BARMITZVAH = "http://gedcomx.org/BarMitzvah";

    /**
     *  A bar mitzvah was changed.
     */
    const BATMITZVAH = "http://gedcomx.org/BatMitzvah";

    /**
     *  A birth fact was changed.
     */
    const BIRTH = "http://gedcomx.org/Birth";

    /**
     *  A burial fact was changed.
     */
    const BURIAL = "http://gedcomx.org/Burial";

    /**
     *  A christening fact was changed.
     */
    const CHRISTENING = "http://gedcomx.org/Christening";

    /**
     *  A cremation fact was changed.
     */
    const CREMATION = "http://gedcomx.org/Cremation";

    /**
     *  A death fact was changed.
     */
    const DEATH = "http://gedcomx.org/Death";

    /**
     *  A military service fact was changed.
     */
    const MILITARYSERVICE = "http://gedcomx.org/MilitaryService";

    /**
     *  A naturalization fact was changed.
     */
    const NATURALIZATION = "http://gedcomx.org/Naturalization";

    /**
     *  An occupation fact was changed.
     */
    const OCCUPATION = "http://gedcomx.org/Occupation";

    /**
     *  A religion fact was changed.
     */
    const RELIGION = "http://gedcomx.org/Religion";

    /**
     *  A residence fact was changed.
     */
    const RESIDENCE = "http://gedcomx.org/Residence";

    /**
     *  A stillbirth fact was changed.
     */
    const STILLBIRTH = "http://gedcomx.org/Stillbirth";

    /**
     *  A fact was changed.
     */
    const FACT = "http://gedcomx.org/Fact";

    /**
     *  A caste fact was changed.
     */
    const CASTE = "http://gedcomx.org/Caste";

    /**
     *  A clan fact was changed.
     */
    const CLAN = "http://gedcomx.org/Clan";

    /**
     *  A national id fact was changed.
     */
    const NATIONALID = "http://gedcomx.org/NationalId";

    /**
     *  A nationality fact was changed.
     */
    const NATIONALITY = "http://gedcomx.org/Nationality";

    /**
     *  A physical description fact was changed.
     */
    const PHYSICALDESCRIPTION = "http://gedcomx.org/PhysicalDescription";

    /**
     *  An ethnicity fact was changed.
     */
    const ETHNICITY = "http://gedcomx.org/Ethnicity";

    /**
     *  A gender was changed.
     */
    const GENDER = "http://gedcomx.org/Gender";

    /**
     *  A note was changed.
     */
    const NOTE = "http://gedcomx.org/Note";

    /**
     *  Name was changed.
     */
    const NAME = "http://gedcomx.org/Name";

    /**
     *  A birth name was changed.
     */
    const BIRTHNAME = "http://gedcomx.org/BirthName";

    /**
     *  An AKA name was changed.
     */
    const ALSOKNOWNAS = "http://gedcomx.org/AlsoKnownAs";

    /**
     *  An married name was changed.
     */
    const MARRIEDNAME = "http://gedcomx.org/MarriedName";

    /**
     *  An nickname was changed.
     */
    const NICKNAME = "http://gedcomx.org/Nickname";

    /**
     *  A died before eight fact was changed.
     */
    const DIEDBEFOREEIGHT = "http://familysearch.org/v1/DiedBeforeEight";

    /**
     *  A tribe name fact was changed.
     */
    const TRIBENAME = "http://familysearch.org/v1/TribeName";

    /**
     *  A birth order fact was changed.
     */
    const BIRTHORDER = "http://familysearch.org/v1/BirthOrder";

    /**
     *  A life sketch was changed.
     */
    const LIFESKETCH = "http://familysearch.org/v1/LifeSketch";

    /**
     *  A title of nobility fact was changed.
     */
    const TITLEOFNOBILITY = "http://familysearch.org/v1/TitleOfNobility";

    /**
     *  A not-a-match declaration
     */
    const NOTAMATCH = "http://familysearch.org/v1/NotAMatch";
}
