<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Atom;

/**
 * conveys information about a category associated with an entry or feed.
 */
class Category extends \Gedcomx\Atom\CommonAttributes
{

    /**
     * identifies a categorization scheme
     *
     * @var string
     */
    private $scheme;

    /**
     * identifies the category to which the entry or feed belongs
     *
     * @var string
     */
    private $term;

    /**
     * a human-readable label for display in end-user applications
     *
     * @var string
     */
    private $label;

    /**
     * Constructs a Category from a (parsed) JSON hash
     *
     * @param array $o
     */
    public function __construct($o = null)
    {
        if ($o) {
            $this->initFromArray($o);
        }
    }

    /**
     * identifies a categorization scheme
     *
     * @return string
     */
    public function getScheme()
    {
        return $this->scheme;
    }

    /**
     * identifies a categorization scheme
     *
     * @param string $scheme
     */
    public function setScheme($scheme)
    {
        $this->scheme = $scheme;
    }
    /**
     * identifies the category to which the entry or feed belongs
     *
     * @return string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * identifies the category to which the entry or feed belongs
     *
     * @param string $term
     */
    public function setTerm($term)
    {
        $this->term = $term;
    }
    /**
     * a human-readable label for display in end-user applications
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * a human-readable label for display in end-user applications
     *
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
    }
    /**
     * Returns the associative array for this Category
     *
     * @return array
     */
    public function toArray()
    {
        $a = parent::toArray();
        if ($this->scheme) {
            $a["scheme"] = $this->scheme;
        }
        if ($this->term) {
            $a["term"] = $this->term;
        }
        if ($this->label) {
            $a["label"] = $this->label;
        }
        return $a;
    }


    /**
     * Initializes this Category from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        parent::initFromArray($o);
        if (isset($o['scheme'])) {
            $this->scheme = $o["scheme"];
        }
        if (isset($o['term'])) {
            $this->term = $o["term"];
        }
        if (isset($o['label'])) {
            $this->label = $o["label"];
        }
    }
}
