<?php

/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

  namespace Gedcomx\Types {

    // Enumeration of known field value types.
    class FieldValueType {
    

      //  The field value is original, extracted directly from the record. What you see is what you get, including misspellings and other errors in the record.
      const Original = "{http://gedcomx.org/}Original";

      //  The field value is interpreted, meaning a user or other automated process applied some reasoning to interpret the value.
      const Interpreted = "{http://gedcomx.org/}Interpreted";
    
    }

  }  
    
?>
