<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Types;

/**
 * Enumeration of known record types.
 */
class RecordType
{

    /**
     *  A record of a person's admission to an institution, society, or other association.
     */
    const ADMISSION = "http://gedcomx.org/Admission";

    /**
     *  A record of an adoption.
     */
    const ADOPTION = "http://gedcomx.org/Adoption";

    /**
     *  An affidavit.
     */
    const AFFIDAVIT = "http://gedcomx.org/Affidavit";

    /**
     *  A person's application to an institution, society or other association.
     */
    const APPLICATION = "http://gedcomx.org/Application";

    /**
     *  A record of a person's arrival at a certain place.
     */
    const ARRIVAL = "http://gedcomx.org/Arrival";

    /**
     *  A bank record.
     */
    const BANK = "http://gedcomx.org/Bank";

    /**
     *  A record of a person's baptism.
     */
    const BAPTISM = "http://gedcomx.org/Baptism";

    /**
     *  A record of a birth.
     */
    const BIRTH = "http://gedcomx.org/Birth";

    /**
     *  A record of a person's burial or interment.
     */
    const BURIAL = "http://gedcomx.org/Burial";

    /**
     *  todo: document this type.
     */
    const BUSINESS = "http://gedcomx.org/Business";

    /**
     *  todo: document this type.
     */
    const CEMETERY = "http://gedcomx.org/Cemetery";

    /**
     *  A census record.
     */
    const CENSUS = "http://gedcomx.org/Census";

    /**
     *  A record of a person's christening.
     */
    const CHRISTENING = "http://gedcomx.org/Christening";

    /**
     *  A record of a person's confirmation.
     */
    const CONFIRMATION = "http://gedcomx.org/Confirmation";

    /**
     *  todo: document this type.
     */
    const CORRESPONDENCE = "http://gedcomx.org/Correspondence";

    /**
     *  A death record.
     */
    const DEATH = "http://gedcomx.org/Death";

    /**
     *  A record of a person's departure from a certain place.
     */
    const DEPARTURE = "http://gedcomx.org/Departure";

    /**
     *  A divorce record.
     */
    const DIVORCE = "http://gedcomx.org/Divorce";

    /**
     *  todo: document this type.
     */
    const DUPLICATE = "http://gedcomx.org/Duplicate";

    /**
     *  A draft record.
     */
    const DRAFT = "http://gedcomx.org/Draft";

    /**
     *  todo: document this type.
     */
    const ESTATE = "http://gedcomx.org/Estate";

    /**
     *  todo: document this type.
     */
    const INDEX = "http://gedcomx.org/Index";

    /**
     *  todo: document this type. what's the difference between this an MarrigeBanns?
     */
    const INTENDEDMARRIAGE = "http://gedcomx.org/IntendedMarriage";

    /**
     *  A land record.
     */
    const LAND = "http://gedcomx.org/Land";

    /**
     *  A legal record.
     */
    const LEGAL = "http://gedcomx.org/Legal";

    /**
     *  A marriage record.
     */
    const MARRIAGE = "http://gedcomx.org/Marriage";

    /**
     *  A marriage affadavit. todo: is this distinguishment necessary? why not just use Marriage?
     */
    const MARRIAGEAFFIDAVIT = "http://gedcomx.org/MarriageAffidavit";

    /**
     *  todo: document this type.
     */
    const MARRIAGEAMENDMENT = "http://gedcomx.org/MarriageAmendment";

    /**
     *  A record of a person's banns of marriage.
     */
    const MARRIAGEBANNS = "http://gedcomx.org/MarriageBanns";

    /**
     *  todo: document this type. why not just use marriage banns?
     */
    const MARRIAGECONSENT = "http://gedcomx.org/MarriageConsent";

    /**
     *  todo: document this type.
     */
    const MARRIAGEDUPLICATE = "http://gedcomx.org/MarriageDuplicate";

    /**
     *  A marriage license. todo: is this distinguishment necessary? why not just use Marriage?
     */
    const MARRIAGELICENSE = "http://gedcomx.org/MarriageLicense";

    /**
     *  todo: document this type. is this distinguishment necessary? why not just use Marriage?
     */
    const MARRIAGERETURNS = "http://gedcomx.org/MarriageReturns";

    /**
     *  todo: document this type. is this distinguishment necessary?
     */
    const MEMBERSHIP = "http://gedcomx.org/Membership";

    /**
     *  A migration record.
     */
    const MIGRATION = "http://gedcomx.org/Migration";

    /**
     *  A military record.
     */
    const MILITARY = "http://gedcomx.org/Military";

    /**
     *  A naturalization record.
     */
    const NATURALIZATION = "http://gedcomx.org/Naturalization";

    /**
     *  A passenger record.
     */
    const PASSENGER = "http://gedcomx.org/Passenger";

    /**
     *  A pension record.
     */
    const PENSION = "http://gedcomx.org/Pension";

    /**
     *  A probate record.
     */
    const PROBATE = "http://gedcomx.org/Probate";

    /**
     *  todo: document this type.
     */
    const RELATEDDOCUMENT = "http://gedcomx.org/RelatedDocument";

    /**
     *  todo: document this type.
     */
    const RELIGIOUSCREEDS = "http://gedcomx.org/ReligiousCreeds";

    /**
     *  A roll.
     */
    const ROLL = "http://gedcomx.org/Roll";

    /**
     *  A tax record.
     */
    const TAX = "http://gedcomx.org/Tax";

    /**
     *  A vital record.
     */
    const VITAL = "http://gedcomx.org/Vital";
}
