<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Types;

/**
 * Enumeration of high-level genealogical resource types.
 */
class ResourceType
{

    /**
     *  A historical record.
     */
    const RECORD = "http://gedcomx.org/Record";

    /**
     *  A collection.
     */
    const COLLECTION = "http://gedcomx.org/Collection";

    /**
     *  A digital artifact, such as a digital image or video.
     */
    const DIGITALARTIFACT = "http://gedcomx.org/DigitalArtifact";

    /**
     *  A physical artifact.
     */
    const PHYSICALARTIFACT = "http://gedcomx.org/PhysicalArtifact";

    /**
     *  A person.
     */
    const PERSON = "http://gedcomx.org/Person";
}
