<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Types;

/**
 * Enumeration of known gender types.
 */
class GenderType
{

    /**
     *  Male.
     */
    const MALE = "http://gedcomx.org/Male";

    /**
     *  Female.
     */
    const FEMALE = "http://gedcomx.org/Female";

    /**
     *  Unknown. Note that this should be used strictly as &quot;unknown&quot; and not to
    *  indicate a type that is not set or not understood.
     */
    const UNKNOWN = "http://gedcomx.org/Unknown";
}
