<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Types;

/**
 * Enumeration of standard name part types.
 */
class NamePartType
{

    /**
     * (no documentation provided)
     */
    const PREFIX = "http://gedcomx.org/Prefix";

    /**
     * (no documentation provided)
     */
    const SUFFIX = "http://gedcomx.org/Suffix";

    /**
     * (no documentation provided)
     */
    const GIVEN = "http://gedcomx.org/Given";

    /**
     * (no documentation provided)
     */
    const SURNAME = "http://gedcomx.org/Surname";
}
