<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Agent;

/**
 * An online account for a web application.
 */
class OnlineAccount extends \Gedcomx\Common\ExtensibleData 
{
    

    /**
     * The name associated the holder of this account with the account.
     */
    private $accountName;
    /**
     * The homepage of the service that provides this account.
     */
    private $serviceHomepage;

    /**
     * Constructs a OnlineAccount from a (parsed) JSON hash
     */
    public function __construct($o = null) {
      if( $o ) {
        $this->initFromArray($o);
      }
    }

    /**
     * The name associated the holder of this account with the account.
     */
    public function getAccountName() {
      return $this->accountName;
    }

    /**
     * The name associated the holder of this account with the account.
     */
    public function setAccountName($accountName) {
      $this->accountName = $accountName;
    }
    /**
     * The homepage of the service that provides this account.
     */
    public function getServiceHomepage() {
      return $this->serviceHomepage;
    }

    /**
     * The homepage of the service that provides this account.
     */
    public function setServiceHomepage($serviceHomepage) {
      $this->serviceHomepage = $serviceHomepage;
    }
    /**
     * Returns the associative array for this OnlineAccount
     */
    public function toArray() {
      $a = parent::toArray();
      if( $this->accountName ) {
            $a["accountName"] = $this->accountName;
      }
      if( $this->serviceHomepage ) {
            $a["serviceHomepage"] = $this->serviceHomepage->toArray();
      }
      return $a;
    }


    /**
     * Initializes this OnlineAccount from an associative array
     */
    public function initFromArray($o) {
      parent::initFromArray($o);
      if( isset($o['accountName']) ) {
            $this->accountName = $o["accountName"];
      }
      if( isset($o['serviceHomepage']) ) {
            $this->serviceHomepage = new \Gedcomx\Common\ResourceReference($o["serviceHomepage"]);
      }
    }
}
