<?php
/**
 *
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 *
 */

namespace Gedcomx\Agent;

/**
 * An online account for a web application.
 */
class OnlineAccount extends \Gedcomx\Common\ExtensibleData
{

    /**
     * The name associated the holder of this account with the account.
     *
     * @var string
     */
    private $accountName;

    /**
     * The homepage of the service that provides this account.
     *
     * @var \Gedcomx\Common\ResourceReference
     */
    private $serviceHomepage;

    /**
     * Constructs a OnlineAccount from a (parsed) JSON hash
     *
     * @param mixed $o Either an array (JSON) or an XMLReader.
     */
    public function __construct($o = null)
    {
        if (is_array($o)) {
            $this->initFromArray($o);
        }
        else if ($o instanceof \XMLReader) {
            $success = true;
            while ($success && $o->nodeType != \XMLReader::ELEMENT) {
                $success = $o->read();
            }
            if ($o->nodeType != \XMLReader::ELEMENT) {
                throw new \Exception("Unable to read XML: no start element found.");
            }

            $this->initFromReader($o);
        }
    }

    /**
     * The name associated the holder of this account with the account.
     *
     * @return string
     */
    public function getAccountName()
    {
        return $this->accountName;
    }

    /**
     * The name associated the holder of this account with the account.
     *
     * @param string $accountName
     */
    public function setAccountName($accountName)
    {
        $this->accountName = $accountName;
    }
    /**
     * The homepage of the service that provides this account.
     *
     * @return \Gedcomx\Common\ResourceReference
     */
    public function getServiceHomepage()
    {
        return $this->serviceHomepage;
    }

    /**
     * The homepage of the service that provides this account.
     *
     * @param \Gedcomx\Common\ResourceReference $serviceHomepage
     */
    public function setServiceHomepage($serviceHomepage)
    {
        $this->serviceHomepage = $serviceHomepage;
    }
    /**
     * Returns the associative array for this OnlineAccount
     *
     * @return array
     */
    public function toArray()
    {
        $a = parent::toArray();
        if ($this->accountName) {
            $a["accountName"] = $this->accountName;
        }
        if ($this->serviceHomepage) {
            $a["serviceHomepage"] = $this->serviceHomepage->toArray();
        }
        return $a;
    }


    /**
     * Initializes this OnlineAccount from an associative array
     *
     * @param array $o
     */
    public function initFromArray($o)
    {
        parent::initFromArray($o);
        if (isset($o['accountName'])) {
            $this->accountName = $o["accountName"];
        }
        if (isset($o['serviceHomepage'])) {
            $this->serviceHomepage = new \Gedcomx\Common\ResourceReference($o["serviceHomepage"]);
        }
    }

    /**
     * Sets a known child element of OnlineAccount from an XML reader.
     *
     * @param \XMLReader $xml The reader.
     * @return bool Whether a child element was set.
     */
    protected function setKnownChildElement($xml) {
        $happened = parent::setKnownChildElement($xml);
        if ($happened) {
          return true;
        }
        else if (($xml->localName == 'accountName') && ($xml->namespaceURI == 'http://gedcomx.org/v1/')) {
            $child = '';
            while ($xml->read() && $xml->hasValue) {
                $child = $child . $xml->value;
            }
            $this->accountName = $child;
            $happened = true;
        }
        else if (($xml->localName == 'serviceHomepage') && ($xml->namespaceURI == 'http://gedcomx.org/v1/')) {
            $child = new \Gedcomx\Common\ResourceReference($xml);
            $this->serviceHomepage = $child;
            $happened = true;
        }
        return $happened;
    }

    /**
     * Sets a known attribute of OnlineAccount from an XML reader.
     *
     * @param \XMLReader $xml The reader.
     * @return bool Whether an attribute was set.
     */
    protected function setKnownAttribute($xml) {
        if (parent::setKnownAttribute($xml)) {
            return true;
        }

        return false;
    }

    /**
     * Writes the contents of this OnlineAccount to an XML writer. The startElement is expected to be already provided.
     *
     * @param \XMLWriter $writer The XML writer.
     */
    public function writeXmlContents($writer)
    {
        parent::writeXmlContents($writer);
        if ($this->accountName) {
            $writer->startElementNs('gx', 'accountName', null);
            $writer->text($this->accountName);
            $writer->endElement();
        }
        if ($this->serviceHomepage) {
            $writer->startElementNs('gx', 'serviceHomepage', null);
            $this->serviceHomepage->writeXmlContents($writer);
            $writer->endElement();
        }
    }
}
